### PR TITLE
Add Entries for MassGib everything 

### PR DESCRIPTION
**Pull request by tomm1996**
Give Everything Except Weapons & Give All Weapons are separate for the purpose of mule creation & dropping armaments at a later point.

I tested the scripts and they seem to run nicely without crashing my client

- Only Runs if isOwnDlc(1)
- Gives Ashes of War three times
- Does not give crafting materials due to max chest space issues

### CODE REVIEW

**Comment by inuNorii** [comment]
I get the idea of "Give Everything except Weapons", but "Give All Weapons" is already in the table.

**Comment by tomm1996** [comment]
@inuNorii fair. For me, it was just the inconvenience of having to do drop them over two separate scripts so I created it like that.
How would you feel about this:

- Give everything
- Give everything except weapons

So I could either make a lvl 1 build & copy it so I can decide later what Upgrade I want or just drop everything including weapons from the get-go. Would you agree with that?

**Comment by inuNorii** [comment]
I have a different solution planned, but it'll take a while until I get around to implementing it. We had GUIs for MassItemGib in our Dark Souls III table and I intend to port those over at some point, removing the need for a lot of the split up scripts in MassItemGib.

**Comment by tomm1996** [comment]
Glad to hear you're working on a GUI, that's awesome! I updated the branch so it makes more sense, in case you want to use that until then. If not, just close the PR it's fine either way

**Comment by Croisade86** [comment]
Hi,
i have used your AOB  and  "Death Num"  (94 offset) for a counter only 
maybe not usable out of my configuration can you test him ?  :

https://github.com/Croisade86/eldenring-counter-python-and-.exe-by-AOB

Best regards.

**Pull request closed without merging**
